export enum TrackedScreen {
  HOME_SCREEN = 'HOME_SCREEN',
  EDIT_PART_SCREEN = 'EDIT_PART_SCREEN',
  SEARCH_SCREEN = 'SEARCH_SCREEN',
  NEW_PIECE_SCREEN = 'NEW_PIECE_SCREEN',
  NEW_PART_SCREEN = 'NEW_PART_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  VIDEO_SCREEN = 'VIDEO_SCREEN',
  SETTINGS_SCREEN = 'SETTINGS_SCREEN',
  PIECE_SCREEN = 'PIECE_SCREEN',
  ADD_PART_SCREEN = 'ADD_PART_SCREEN',
  USER_SCREEN = 'USER_SCREEN',
  PLAYER_SCREEN = 'PLAYER_SCREEN',
}
