export enum TrackedEvent {
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  LOGOUT = 'LOGOUT',
  SCREEN_VIEW = 'SCREEN_VIEW',
  PRESS = 'PRESS',
  AUDIO_PERMISSION_REQUEST = 'AUDIO_PERMISSION_REQUEST',
}
