export enum TrackedComponentLocation {
  PIECE_CAROUSEL = 'PIECE_CAROUSEL',
  FLOATING_PLAYER_CAROUSEL = 'FLOATING_PLAYER_CAROUSEL',
  ADD_PART_BUTTON = 'ADD_PART_BUTTON',
  SIGN_UP_FORM = 'SIGN_UP_FORM',
}
